### ISSUE TITLE
Add speed parameter

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/readme-typing-svg#12]
**Allow changing the animation duration with a URL parameter.**

Currently, the speed is always the same (4 seconds to type and 1 second to delete) regardless of how wide the image output is.

For an image that's not very wide, this is extremely slow.

A url parameter, for example `duration`, which takes a number in seconds and scales the animation to that length would be useful in this case.

**Alternatively,** we could make `speed` be a parameter and have the duration calculated from speed with an inverse function (eg. `50 / $speed` or something similar) - see [comment](https://github.com/DenverCoder1/readme-typing-svg/issues/12#issuecomment-830871441). 

If `speed` is used, the width of the SVG can also be taken into account so that it is a consistent speed for any size (see [comment](https://github.com/DenverCoder1/readme-typing-svg/issues/12#issuecomment-830874252)). If `duration` is used, this is not an issue.

**Comment by Evavic44** [comment]
I'm a little bit confused with this issue. Are you requesting the speed value is increased? 🤔

**Comment by DenverCoder1** [comment]
@Evavic44 Basically, what needs to be added is a new url parameter (like the options [here](https://github.com/DenverCoder1/readme-typing-svg#-options)) that can take in a number of seconds to use instead of "5" in the SVG template.

So you can say something like `/?lines=text&duration=3` and it will make the text type and delete in 3 seconds instead of 5.

**Comment by DenverCoder1** [comment]
There are 2 places in the main.php template where `5` need to be replaced with `<?php echo $duration ?>`

![image](https://user-images.githubusercontent.com/20955511/116637976-f280f880-a96d-11eb-9319-0d16b786f58a.png)

The `$duration` variable should come from the `RendererView` which gets info from the `RendererModel` that will validate the requested parameter. So a new field will need to be created in the model and the existing `checkNumber` function can be used to validate it.

**Comment by 8BitJonny** [comment]
I would argue that instead of directly controlling the `dur` value in seconds, it would be more handy to have a user exposed value that represents the typing speed.

### An example:
Imagine controlling the animation `duration` in seconds when you have two lines of text to be animated. `First Line` & `Second line of text that is very long` as our two lines. Now setting the animation duration equal to 2s would mean a rather moderate typing speed for the short `First line` but a very, very fast typing speed for the long second line, because the animation needs to type alot more characters in the same 2 seconds that it had for the short line.

Therefore I would suggest having a value that represents the milliseconds per character. When for example we have a standard typing speed of 250ms per character then a 10 letter line would take 2,5seconds to animate and a 20 letter line would take 5seconds.

All you have to do inside `main.php` is to replace the `dur=5` with something like `dur=<?php echo $typingSpeed / $lines[$i] ?>` (not tested pseudo code, but you get the idea)

**Comment by DenverCoder1** [comment]
Hi @8BitJonny, the way it currently works is that `dur` is the number of seconds to draw a single path from 0 to 100% of the width. So, as it is, the typing speed is the always the same regardless of how many lines there are or how long the lines are (there could be a slight pause after short lines finish typing, though).

This GIF with the path and border shown may help to visualize it:

![stroke-shown](https://user-images.githubusercontent.com/20955511/116822820-af02d600-ab89-11eb-82f8-32013cf7918b.gif)

We could make a parameter for speed instead, but it would be inversely proportional to the duration.

**Comment by 8BitJonny** [comment]
Oh, then I'm terribly sorry. Then I completely misunderstood the `duration` property.
Thanks for showing me that 👍🏼  I'll take everything back

**Comment by DenverCoder1** [comment]
@8BitJonny No problem. I actually think you're idea of the user controlling the "speed" instead of "duration" is more intuitive. The calculation could be something like `duration = 50 / $speed` or something similar, though.

**Comment by 8BitJonny** [comment]
That sound also interesting. I would say both `duration` or `speed` are equally intuitive if the wording is carefully chosen in the documentation. Because `duration` indicates the animation duration while the `speed` indicates the speed with which the letters are typed.
I think you could argue for both.

> The calculation could be something like duration = 50 / $speed or something similar, though.

But wouldn't the calculation needed to be based on the width? I just generated a svg with width 200 and a second svg with with 2000px. This is of course taken to the extreme but the duration is the same for both, but the typing speed equals more like Flash in the second svg

![](https://media.giphy.com/media/xUOxeZUc8UFwMgH2MM/giphy-downsized.gif)

**Comment by DenverCoder1** [comment]
@8BitJonny You are right, this is something that could be taken into account.

**Comment by BenjaminMichaelis** [comment]
This could be interesting, is this in the works?

**Comment by DenverCoder1** [comment]
There's no progress yet, but it likely won't be difficult to add

**Comment by BenjaminMichaelis** [comment]
I will try to throw something together for this quickly!
